### ISSUE TITLE
Outline

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/landsat-mosaic-latest#3]
- SNS message comes in
- ~Load metadata from DynamoDB to know quadkey zoom, or potentially provide it as an environment variable~. Don't need to know this, because it's specified in the pre-generated pathrow-quadkey index.
- Find new asset(s)

    ```py
    with open('example.json') as f:
        body = json.load(f)

    message = json.loads(body['Message'])

    records = message['Records']
    record = records[0]
    ```

- For each asset:
	- Retrieve metadata. The metadata is in a `*_MTL.json` file in the same directory as the `index.html` referenced in the SNS message. So you'll have to do an S3 List, and then retrieve the JSON file. The structure of the JSON file is listed in #4.
	- If cloud cover is above designated level, return
	- Find overlapping quadkeys from path-row to quadkey index
	- For each overlapping mercator tile:
		- Find existing dynamoDB payload
		- Add new image
		- Find out which of the existing images can be removed with the addition of the new image, while still covering the entire tile. Remove these.
		- Write back to DynamoDB

### To do

- [x] Create path-row to quadkey index

**Comment by vincentsarago** [comment]
> Find out which of the existing images can be removed with the addition of the new image, while still covering the entire tile. Remove these.

I think this can be done by keeping only one Path/row scene per tile, see https://github.com/developmentseed/awspds-mosaic/blob/master/awspds_mosaic/landsat/stac.py#L119-L126

To get info from the sceneID you can use https://github.com/cogeotiff/rio-tiler/blob/v2/rio_tiler/io/landsat8.py#L30

> Retrieve metadata. The metadata is in a *_MTL.json file in the same directory as the index.html referenced in the SNS message. So you'll have to do an S3 List, and then retrieve the JSON file. The structure of the JSON file is listed in #4.

The problem with MTL from landsat, is that you cannot get the data geometry, you'll get the bbox of the data (covering the nodata part), you can overcome this by getting the bounds using the BQA band see: https://github.com/vincentsarago/landsat-footprint

Maybe the easiest way to achieve `scene <-> quadkey tile` would be to create a lookup table (txt file) referencing each Path/row for each quadkey (I think it should fit in the lambda code) thus you don't need to read any file.

(Note if you want to exclude based on cloud, you'll need to read the MTL file)

**Comment by kylebarron** [comment]
Thanks for the comments 🙂

> I think this can be done by keeping only one Path/row scene per tile

Yeah I understand this now.

> To get info from the sceneID you can use

Yes, I'll definitely use that for parsing!

> Maybe the easiest way to achieve `scene <-> quadkey tile` would be to create a lookup table (txt file) referencing each Path/row for each quadkey (I think it should fit in the lambda code) thus you don't need to read any file.

I think you're right. I can have a script to create that data file from the [public shapefiles](https://www.usgs.gov/land-resources/nli/landsat/landsat-shapefiles-and-kml-files). (I didn't know there were nighttime landsat files...)

> (Note if you want to exclude based on cloud, you'll need to read the MTL file)

I do want to exclude based on cloud, so that I can have a "current cloudless" mosaic. But since this is a "backend script" and a user isn't waiting on this, milliseconds don't count 🙂
